% Generated by roxygen2: do not edit by hand
% Please edit documentation in R/edges.tree.R
\name{edges.tree}
\alias{edges.tree}
\title{Title}
\usage{
\method{edges}{tree}(input_object, ...)
}
\arguments{
\item{...}{}
}
\description{
Title
}
